### ISSUE TITLE
Can not reconnect after the connection is disconnected

### ISSUE THREAD

**Issue by qhd12345** [bridgefy/sdk-android-beta#14]
**Describe the bug**
Two devices can connect stably, but after the connection is unexpectedly disconnected, they cannot reconnect.

**To Reproduce**
1. Init Bridgefy on two device and make sure they are connected.
2. Turn on/off Network(May cause the connection to be disconnected)
3. They will not reconnect.

**Expected behavior**
Reconnect after disconnected.

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy XCover 5]
 - OS: [Android 11]

**Comment by julian-bridgefy** [comment]
We're excited to announce the official release of the Bridgefy SDK for Android, and we'd like to invite you to update your beta version to the latest release. This is a significant milestone for us, and we couldn't have done it without your valuable feedback and support during the beta phase.

### What's New in the Bridgefy SDK Android Release:

**Enhanced Stability:** We've made substantial improvements to ensure the stability and reliability of the Bridgefy SDK, ensuring it performs seamlessly in various scenarios.

**Performance Boost:** You'll notice a significant enhancement in performance, including reduced battery consumption and improved message delivery.

**New Features:** We've added some exciting features that expand the capabilities of the SDK, providing more flexibility and options for your projects.

**Bug Fixes:** Numerous issues reported during the beta phase have been addressed in this release.

### How to Update:

To update your beta version to the official release, follow these simple steps:

* Visit the Bridgefy Developer Portal (https://developer.bridgefy.me/).
* Log in to your account.
* Follow the installation and update instructions in the documentation to seamlessly transition to the new release.

### Feedback and Support:

We are committed to continuously improving the Bridgefy SDK and providing you with the best tools for your projects. If you encounter any issues, have questions, or want to share your feedback, please don't hesitate to reach out to our dedicated support team at [support@bridgefy.me](mailto:contact@bridgefy.me).



Your feedback is invaluable to us, and we look forward to hearing about your experiences with the new release.
