### ISSUE TITLE
MissingApplicationIdException(error=License is not valid)

### ISSUE THREAD

**Issue by qhd12345** [bridgefy/sdk-android-beta#16]
Got MissingApplicationIdException(error=License is not valid: xxx.xxx.xx ). I init bridgefy like this:
bridgefy.init(UUID.fromString(BuildConfig.BridgefyKey),PropagationProfile.Standard,delegate)
The Api key and application ID are correct.

1. init bridgefy and wait for a while

 - Device: Galaxy XCover 5
 - OS: Android 11
 - bridgefy version: android-sdk:0.4.0

**Comment by julian-bridgefy** [comment]
Hello, thank you for reporting the issue, it's a license bug, it seems that the property is required in both the AndroidManifest and the SDK. 
Add this meta-data values on AndroidManifest:
```xml
<meta-data
            android:name="com.bridgefy.sdk.API_KEY"
            android:value="${BridgefyKey}" />
```
