### ISSUE TITLE
InternetConnectionRequiredException

### ISSUE THREAD

**Issue by qhd12345** [bridgefy/sdk-android-beta#19]
Can not init Bridgefy with onFailToStart:InternetConnectionRequiredException(error=It has not been possible to validate the SDK, check your internet connection or try again, if the problem persists contact the Bridgefy team.)

Code for initialization:
`bridgefy = Bridgefy(MyApplication.context)
bridgefy?.init(null,UUID.fromString(BuildConfig.BridgefyKey),PropagationProfile.Standard,delegate)`

I also add Bridgefy API key in manifest
`<meta-data
            android:name="com.bridgefy.sdk.API_KEY"
            android:value="${bridgefyKey}" />`

init bridgefy and wait for a while

Device: Galaxy XCover 5
OS: Android 11
bridgefy version: android-sdk:1.0.0

**Comment by julian-bridgefy** [comment]
This is a Beta project and We have a new version available.
If you have created an account on [developer.bridgefy.me](https://developer.bridgefy.me), it is necessary to update the production SDK. 
Here is the official [bridgefy sdk](https://github.com/bridgefy/sdk-android).
