### ISSUE TITLE
Getting InternetConnectionRequiredException when initializing

### ISSUE THREAD

**Issue by mesrob-crew** [bridgefy/sdk-android-beta#3]
**Describe the bug**
Note: I am testing the Android SDK via Flutter wrapper. When calling init() I get an exception InternetConnectionRequiredException(error=Bad Request). The mobile device does have an internet connection. None of the delegate callbacks are getting invoked. 

**To Reproduce**
1. Call init() via Android SDK.

**Expected behavior**
To initialize the SDK and call the onStarted() delegate callback.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android
 - Version: 12

**Additional context**
Have written the test application via Flutter wrapper but am debugging the native Android code that is calling the Bridgefy SDK.

**Comment by mesrob-crew** [comment]
Turned out to be fault on my end, the package ID of my test app didn't match up with the App ID in the Bridgefy License. Figured it out as the iOS error code was more accurate "License validation error" vs the Android one above which can be adjusted to match with the iOS error code.

**Comment by yachaka** [comment]
Thank you I had the same issue without understanding
